### ISSUE TITLE
Flexslider used in ngRepeat only shows last one due to compile

### ISSUE THREAD

**Issue by moritzschaefer** [thenikso/angular-flexslider#20]
As commented in this stackoverflow there is an issue due to the fact that flexslider handles all its logic in the compile-method:

http://stackoverflow.com/questions/24059492/angularjs-only-shows-last-element-in-ng-repeat/24067352#24067352

I will try to write a fix and will send a pull request, though I am not sure if I am able to fix this one.

**Comment by scandeiro** [comment]
Ok, it example demonstrate multiple sliders working together, but how can we solve the "two-way binding" issue?
