### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by manojktechie** [thenikso/angular-flexslider#26]
Hi,

I am getting TypeError: undefined is not a function on line  return flexsliderDiv.flexslider(options); What may be the reason? Please help.

Regards

**Comment by wesleyfsmith** [comment]
Thank you... this totally saved me.

**Comment by renttless** [comment]
Thanks oroger, solved the problem.. anybody any idea why this happened?

**Comment by thenikso** [comment]
hi there! what was the initial import order? 

Depending on that the problem may be that angular uses jQuery instead of an embedded "jqlite" if it is defined before angular itself. so yes, @oroger import is the correct one as reported in the "setup" section of the readme

**Comment by Devendra17** [comment]
Thanks Oroger, This is relay working. Solved my problem.
But I have another issue TypeError: $(...).data(...) is undefined.

When i click next prev some time this error are creating. Please Help me.
