### ISSUE TITLE
How would I add markup to the control nav thumbnails 

### ISSUE THREAD

**Issue by sgtsaughter** [thenikso/angular-flexslider#30]
I have successfully set up a thumbnail control nav slide show based on your example in examples/thumbnail-controlnav.html 

```
<flex-slider slide="s in slides" animation="slide" control-nav="thumbnails">
        <li data-thumb="{{s}}">
            <img ng-src="{{s}}">
        </li>
</flex-slider>
```

I would like to add markup (text and font icons) to the thumbnails, but it seems like angular-flexslider is generating the markup for the thumbnails.  Is it possible to add the markup I want to the thumbnails?

Thanks.

**Comment by thenikso** [comment]
It is working in here, if you change the bottom slider the top one follows. can you confirm?

**Comment by inkodus** [comment]
Have same problem and Plunker is not working. Says: 
```javascript
Refused to execute script from 'https://raw.githubusercontent.com/thenikso/angular-flexslider/master/angular-flexslider.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
And of course module 'angular-flexslider' is not available.

**Comment by thenikso** [comment]
Here you go http://plnkr.co/edit/AiGSr6?p=preview
