### ISSUE TITLE
Cannot read property 'animating' of undefined

### ISSUE THREAD

**Issue by kozer** [thenikso/angular-flexslider#35]
I have an issue, trying to do this example:
http://flexslider.woothemes.com/thumbnail-slider.html

This is the plunker:

http://plnkr.co/edit/K4VBoSqCAFbr1Fps0JJr

I set up all properties but when i click on "carousel" i get Cannot read property 'animating' of undefined.Can anyone help me to solve this? Is this a bug? 

Thanks a lot

**Comment by thenikso** [comment]
the error is resolved by referencing the correct element in `sync` and `as-nav-for`. in the example punkr one could remove the `slider-id` and have:

```
<flex-slider id="slider" sync="#slider2 .flexslider" ...></flex-slider>
...
<flex-slider id="slider2" as-nav-for="#slider .flexslider" ...></flex-slider>
```
