### ISSUE TITLE
Issues with width

### ISSUE THREAD

**Issue by coopersita** [thenikso/angular-flexslider#38]
I'm having an issue with my slider. The slides (which are text, instead of images) all have a width of 0 pixels, so they are all bunch up on top of each other.

Here's my code:

```
<div ng-show="gameStatus == 'turnPick'">
	
<flex-slider slide="q in player.questions track by q.id" after="currentSlide($slider)" slideshow="false" animation="slide">
    <li ng-bind-html="q.content"></li>
</flex-slider>

</div>
```

I've done some tests, and if I take the ng-show off from the container div, it works well, but I only want the slideshow to display at certain points during the interactions.

**Comment by thenikso** [comment]
if there is no images forcing the size it may be needed to specify a width via CSS. does the problem present itself if you use flexslider alone?

**Comment by thenikso** [comment]
Closing this for now
