### ISSUE TITLE
Unable to remove last slide in the container

### ISSUE THREAD

**Issue by palinda** [thenikso/angular-flexslider#40]
This is due to following watchCollection,

 return $scope.$watchCollection(collectionString, function(collection) {
         .......
              if (!(collection != null ? collection.length : void 0)) { ///<- watch only new value. So when we remove last item in the data collection it's length become 0. That makes it return without removing the slide. 
               
 return;
              }
         ........

Suggested solution : 

return $scope.$watchCollection(collectionString, function(collection, oldCollection) {
           ......
              if (!(collection != null ? collection.length : void 0) && !(oldCollection != null ? oldCollection.length : void 0)) {
                return;
              }
.......

**Comment by thenikso** [comment]
Nice catch thanks! would you be able to open a pull request for this?

**Comment by palinda** [comment]
Thanks. Yeah. I did the change.

**Comment by jaime-franco** [comment]
Hi, i'm facing the same issue right know

**Comment by palinda** [comment]
Hi Jaime,

As I mentioned in the first comment this issue can fix by watching old Collection.

***********************
return $scope.$watchCollection(collectionString, function(collection, oldCollection) {
......
if (!(collection != null ? collection.length : void 0) && !(oldCollection != null ? oldCollection.length : void 0)) {
return;
}
************************

change snpashot.
![image](https://cloud.githubusercontent.com/assets/4861148/5931667/98e67a4e-a6c6-11e4-9a10-30f8e00f39c2.png)

**Comment by jaime-franco** [comment]
@palinda  Thanks, Actually i had doubt about adding the oldCollection (This is something that angular handle by itself?)

**Comment by thenikso** [comment]
thanks @palinda, #44 has been merged
