### ISSUE TITLE
Changing the value in scope doesn't change the values in slider.The slider continues to work with the first value assigned to it.

### ISSUE THREAD

**Issue by JayavasanthRamesh** [thenikso/angular-flexslider#43]
I have to update the details displayed in slider once the whole animation is over. So I called a function using the end attribute of the slider to update the data displayed in the slider.

But the replaced vaues doesn't reflect in the slider. Slider displays the first text it was assigned with.

An sample of the same format 
http://plnkr.co/edit/XBt2frXArITSiyToaNWK?p=preview

**Comment by jaime-franco** [comment]
Hey, hi @JayavasanthRamesh  the problem with your example is that yo have to define a function with var not $scope.nameFunction = function...

http://plnkr.co/edit/zIftjwXBqk70wwPqwI7L?p=preview

**Comment by thenikso** [comment]
Great fix @jaime-franco thank! @JayavasanthRamesh I guess this fixes it!
