### ISSUE TITLE
can't work with examples

### ISSUE THREAD

**Issue by arizona1973** [thenikso/angular-flexslider#46]
I had to change the path for jquery.js in the example code

../bower_components/jquery/jquery.js  => ../bower_components/jquery/src/jquery.js

but now,

I've got the errors

jquery.js:1                      Uncaught ReferenceError: define is not defined  
jquery.flexslider.js:1157 Uncaught ReferenceError: jQuery is not defined
angular.js:11598             TypeError: undefined is not a function
    at angular-flexslider.js:168
    at angular.js:16210
    at completeOutstandingRequest (angular.js:4902)
    at angular.js:5282angular.js:11598 (anonymous function)

the jquery.js:1 seems fine, what else do i need to make it works?  Thank You

**Comment by thenikso** [comment]
this should have been fixed by #45
