### ISSUE TITLE
Casing of property names in the readme

### ISSUE THREAD

**Issue by umpirsky** [thenikso/angular-flexslider#52]
In [README](https://github.com/thenikso/angular-flexslider#properties) there are properties documented.

I tried for example `startAt="3"` and it didn't worked. I almost gave up when I tried `start-at="3"` and it worked.

Looks like README needs an update?

**Comment by thenikso** [comment]
There is a note in the "properties" section saying:

> For example, the property controlNav can be specified via the attribute control-nav.

The properties names reported are the one from flexslider itself.

**Comment by umpirsky** [comment]
@thenikso Oh, my bad, sorry, missed that. Thanks.

**Comment by thenikso** [comment]
:+1:
