### ISSUE TITLE
unable to set the slideshow speed

### ISSUE THREAD

**Issue by dataonline** [thenikso/angular-flexslider#54]
From the documentation

...
 flex-slider flex-slide="s in thumbnails" slideshowSpeed="1000" animation="slide" animation-loop="true" item-width="210" item-margin="5"

...
should alter the slideshow speed. This does appear to be the correct way to alter the speed.

**Comment by dataonline** [comment]
please ignore, I have found the snake and camel case comment and obviously did not understand it.

**Comment by thenikso** [comment]
:+1:
