### ISSUE TITLE
Using with Yeoman

### ISSUE THREAD

**Issue by RemeJuan** [thenikso/angular-flexslider#55]
I got everything working with little effort, just putting this here as it may be useful to other and could be considered part of the readme perhaps.

I am using the yeoman angular app/build config so the bower section of scripts gets dynamically built in the HTML file when 'grunt serve' is run or 'bower.json' is updated.

A quick update to the json file ensured that I had all the correct files in the correct order.

I did however need to make 1 change to "flexslider\.bower.json"

"main": "./jquery.flexslider.js",

needed to be added in under main. Doing that and updating the bower.json file of the app ensures that everything loads every time and in the correct order that is required.

Thanks for the port I guess, it is working very well on my side.

**Comment by dataonline** [comment]
I too am using the yeoman framework, I posted an issue  a few days ago. Have you been able to configure the slide show speed. It is not reacting to my changes.

**Comment by RemeJuan** [comment]
@dataonline, never tried to change the settings, was happy with the defaults.

**Comment by thenikso** [comment]
Thanks for the hint. so @RemeJuan do you think we should make that bower.json change standard?

**Comment by RemeJuan** [comment]
@thenikso, I am not sure it would be required, however at the same time I do not think it would negatively impact others.

In my scenario when installing, if this line is present the --save switch would also write it into the bower section of my html, at processing time it also uses the same reference during the preparehtml function as then it runs through the bower config to make sure all the files referenced actually exist, but its existence is determined by the file references in the bower.json for each plugin.

For me without that reference, the file gets removed from the HTML at build time. It is possible that anyone using a similar setup, not specifically yoeman, would run into the same issue.

If not adding it as a default maybe to the FAQ or as a note in the README.

**Comment by thenikso** [comment]
Well this issue should provide some documentation on it. I'm not confident on making the change myself as I have not the time to replicate the problem here. Feel free to open a PR tho!
